cfg: !!python/object:config.Config
  accumulate_grad_batches: 8
  backbone_lr: 9.656415071609533e-06
  batch_size: 24
  device: 0
  early_stopping_patience: 3
  learning_rate: 3.878212903999528e-05
  max_epochs: 10
  max_length: 384
  n_runs: 5
  n_test: -1
  n_train: -1
  ollama_url: http://localhost:11434
  scheduler: linear
  warmup_steps: 750
  weight_decay: 0.008229945321501788
