cfg: !!python/object:config.Config
  accumulate_grad_batches: 2
  backbone_lr: 2.0e-05
  batch_size: 8
  device: 0
  learning_rate: 0.0001
  max_epochs: 50
  max_length: 320
  n_runs: 1
  n_test: -1
  n_train: -1
  ollama_url: http://localhost:11434
  warmup_steps: 1500
  weight_decay: 0.01
