cfg: !!python/object:config.Config
  accumulate_grad_batches: 4
  backbone_lr: 1.0e-05
  batch_size: 32
  device: 0
  early_stopping_patience: 3
  learning_rate: 2.0e-05
  max_epochs: 20
  max_length: 256
  n_runs: 5
  n_test: -1
  n_train: -1
  ollama_url: http://localhost:11434
  scheduler: linear
  warmup_steps: 1000
  weight_decay: 0.01
