cfg: !!python/object:config.Config
  accumulate_grad_batches: 2
  backbone_lr: 1.616596762674602e-05
  batch_size: 32
  device: 0
  early_stopping_patience: 3
  learning_rate: 1.734941759188987e-05
  max_epochs: 10
  max_length: 256
  n_runs: 5
  n_test: -1
  n_train: -1
  ollama_url: http://localhost:11434
  scheduler: cosine
  warmup_steps: 500
  weight_decay: 0.00772195789599923
