cfg: !!python/object:config.Config
  accumulate_grad_batches: 2
  backbone_lr: 6.2740487312645126e-06
  batch_size: 32
  device: 0
  early_stopping_patience: 3
  learning_rate: 3.832442972726729e-05
  max_epochs: 10
  max_length: 512
  n_runs: 5
  n_test: -1
  n_train: -1
  ollama_url: http://localhost:11434
  scheduler: linear
  warmup_steps: 1500
  weight_decay: 0.009318571979183506
