cfg: !!python/object:config.Config
  accumulate_grad_batches: 4
  backbone_lr: 3.0e-05
  batch_size: 2
  device: 0
  learning_rate: 5.0e-05
  max_epochs: 40
  max_length: 256
  n_runs: 1
  n_test: -1
  n_train: -1
  ollama_url: http://localhost:11434
  warmup_steps: 1500
  weight_decay: 0.01
