cfg: !!python/object:config.Config
  batch_size: 16
  device: 0
  learning_rate: 2.0e-05
  max_epochs: 3
  max_length: 256
  n_runs: 1
  n_test: 20
  n_train: 100
  ollama_url: http://localhost:11434
